"""init tables

Revision ID: 56d7d6c8be31
Revises: 
Create Date: 2025-09-01 21:47:45.269149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import types as geo_types


# revision identifiers, used by Alembic.
revision: str = '56d7d6c8be31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrations',
    sa.Column('administration_id', sa.Integer(), nullable=False),
    sa.Column('administration_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('administration_id'),
    sa.UniqueConstraint('administration_name')
    )
    op.create_index(op.f('ix_administrations_administration_id'), 'administrations', ['administration_id'], unique=False)
    op.create_table('administration_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administration_id', sa.Integer(), nullable=False),
    sa.Column('boundary', geo_types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('danger_zone',geo_types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('path_zone', geo_types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['administration_id'], ['administrations.administration_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_administration_zones_boundary', 'administration_zones', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_administration_zones_danger_zone', 'administration_zones', ['danger_zone'], unique=False, postgresql_using='gist')
    op.create_index('idx_administration_zones_path_zone', 'administration_zones', ['path_zone'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_administration_zones_id'), 'administration_zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administration_zones_id'), table_name='administration_zones')
    op.drop_index('idx_administration_zones_path_zone', table_name='administration_zones', postgresql_using='gist')
    op.drop_index('idx_administration_zones_danger_zone', table_name='administration_zones', postgresql_using='gist')
    op.drop_index('idx_administration_zones_boundary', table_name='administration_zones', postgresql_using='gist')
    op.drop_table('administration_zones')
    op.drop_index(op.f('ix_administrations_administration_id'), table_name='administrations')
    op.drop_table('administrations')
    # ### end Alembic commands ###
